### ISSUE TITLE
OSError: SavedModel file does not exist at: ./converter/tf_model/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by PaulKassis** [omerferhatt/torch2tflite#2]
Hi,

Thank you very much for sharing this code. I have tried applying it to my torch model, the conversion steps from torch to ONNX and ONNX to TF work fine, but it fails at the last step (TF to TFlite) with the following message:

Traceback (most recent call last):
  File "converter.py", line 58, in <module>
    main()
  File "converter.py", line 22, in main
    convert(torch_model_path=args.torch_model_path,
  File "/home/A49175/torch2tflite-master/converter/torch_to_tflite.py", line 157, in convert
    tf_to_tf_lite(tf_path=TF_PATH, tf_lite_path=tf_lite_model_path)
  File "/home/A49175/torch2tflite-master/converter/torch_to_tflite.py", line 74, in tf_to_tf_lite
    converter = tf.lite.TFLiteConverter.from_saved_model(tf_path)  # Path to the SavedModel directory
  File "/home/A49175/.conda/envs/tflite-converter/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 399, in from_saved_model
    saved_model = _load(saved_model_dir, tags)
  File "/home/A49175/.conda/envs/tflite-converter/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 578, in load
    return load_internal(export_dir, tags)
  File "/home/A49175/.conda/envs/tflite-converter/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 588, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/A49175/.conda/envs/tflite-converter/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/home/A49175/.conda/envs/tflite-converter/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ./converter/tf_model/{saved_model.pbtxt|saved_model.pb}

Do you have any idea of the origin of this problem ? I am using the packages versions specified in the requirements.txt.

Thank you!

**Comment by marziehoghbaie** [comment]
I have the same bug

**Comment by omerferhatt** [comment]
Hello, @PaulKassis and @marziehoghbaie. I didn't check that repo for a long time. I'll look that. Thanks for the feedback.

**Comment by PaulKassis** [comment]
Hi @omerferhatt  and @marziehoghbaie ,
Actually I solved this by upgrading my tensorflow to 2.3.0.

**Comment by omerferhatt** [comment]
Thank you, I updated the relative path and TensorFlow version requirement
