### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by thongvhoang** [omerferhatt/torch2tflite#6]
I tried this code to convert my custom trained YOLOv5 model (.pt)
It returns this bug:
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

2021-06-02 03:17:26.651552: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Showing result!

Traceback (most recent call last):
  File "converter.py", line 59, in <module>
    main()
  File "converter.py", line 30, in main
    original_image, tf_lite_image, torch_image = get_example_input(args.test_im_path)
  File "/content/drive/My Drive/Univoice/yolov5/torch2tflite/converter/torch_to_tflite.py", line 28, in get_example_input
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

How can I fix this?

**Comment by mozeqiu** [comment]
Check your picture path

**Comment by omerferhatt** [comment]
Hello @mozeqiu and @thongvhoang. Please check last version.
